version: '3.7'
services:
  wscef:
    container_name: wscef
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    cap_drop:
      - ALL
    cap_add:
      - SETUID
      - SETGID
      - AUDIT_WRITE
      - DAC_OVERRIDE
      - CAP_SYS_PTRACE
      - CAP_CHOWN
    security_opt:
      - no-new-privileges:true
    environment:
      - LANG=pt_BR.UTF-8
      - TZ=${TZ:-America/Sao_Paulo}
      - DISPLAY=${DISPLAY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    shm_size: 2g
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTHORITY}:/tmp/.docker.xauth:ro
      - ${BANKFILES:-./run/}:/mnt/bankfiles
      #- /etc/machine-id:/etc/machine-id:ro - IDK why if it's used
